spring.application.name=oracle

spring.datasource.url=jdbc:postgresql://localhost:5434/oracle
spring.jpa.hibernate.ddl-auto=validate
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.flyway.schemas=oracle
management.endpoints.web.exposure.include=health,info,metrics
