spring.application.name=oracle

spring.datasource.url=jdbc:postgresql://localhost:5434/oracle
spring.datasource.username=oracle
spring.datasource.password=oracle
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.default_schema=oracle
spring.jpa.open-in-view=false
spring.jpa.packages-to-scan=ru.stepanov.oracle.infrastructure.persistence.entity
spring.flyway.default-schema=oracle
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.flyway.schemas=oracle
management.endpoints.web.exposure.include=health,info,metrics
